// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Clase02Modulo03.Domain.Entities
{
    public partial class Actor
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string NombreArtistico { get; set; }
        public int Edad { get; set; }
        public string Nacionalidad { get; set; }
        public string Genero { get; set; }
    }
}